<?php

defined('ABSPATH') || exit;

class AngellEYE_PayPal_PPCP_Error {

    protected static $_instance = null;
    public $avs_code;
    public $cvv_code;
    public $response_code;
    public $payment_advice_code;

    public static function instance() {
        if (is_null(self::$_instance)) {
            self::$_instance = new self();
        }
        return self::$_instance;
    }

    public function __construct() {
        $this->avs_code = array(
            '0' => array('MAESTRO' => 'All address information matches.'),
            '1' => array('MAESTRO' => 'None of the address information matches.'),
            '2' => array('MAESTRO' => 'Part of the address information matches.'),
            '3' => array('MAESTRO' => 'The merchant did not provide address information. It was not processed.'),
            '4' => array('MAESTRO' => 'The address was not checked, or the acquirer had no response. The service is not available.'),
            'A' => array('VISA' => 'The address matches, but the zip code does not match.', 'MASTERCARD' => 'The address matches, but the zip code does not match.', 'DISCOVER' => 'The address matches, but the zip code does not match.', 'AMEX' => 'The cardholder\'s address is correct.'),
            'B' => array('VISA' => 'The address matches.', 'MASTERCARD' => 'The address matches.', 'DISCOVER' => 'The address matches.'),
            'C' => array('VISA' => 'No values match.', 'MASTERCARD' => 'No values match.', 'DISCOVER' => 'No values match.'),
            'D' => array('VISA' => 'The address and postal code match.', 'MASTERCARD' => 'The address and postal code match.', 'DISCOVER' => 'The address and postal code match.'),
            'E' => array('VISA' => 'Not allowed for internet or phone transactions.', 'MASTERCARD' => 'Not allowed for internet or phone transactions.', 'DISCOVER' => 'Not allowed for internet or phone transactions.', 'AMEX' => 'The name is incorrect, but the address and postal code match.'),
            'F' => array('VISA' => 'The address and postal code match.', 'MASTERCARD' => 'The address and postal code match.', 'DISCOVER' => 'The address and postal code match.', 'AMEX' => 'The name is incorrect, but the address matches.'),
            'G' => array('VISA' => 'Global is unavailable. Nothing matches.', 'MASTERCARD' => 'Global is unavailable. Nothing matches.', 'DISCOVER' => 'Global is unavailable. Nothing matches.'),
            'I' => array('VISA' => 'International is unavailable. Not applicable.', 'MASTERCARD' => 'International is unavailable. Not applicable.', 'DISCOVER' => 'International is unavailable. Not applicable.'),
            'M' => array('VISA' => 'The address and postal code match.', 'MASTERCARD' => 'The address and postal code match.', 'DISCOVER' => 'The address and postal code match.', 'AMEX' => 'The name, address, and postal code match.'),
            'N' => array('VISA' => 'Nothing matches.', 'MASTERCARD' => 'Nothing matches.', 'DISCOVER' => 'Nothing matches.', 'AMEX' => 'The address and postal code are both incorrect.'),
            'P' => array('VISA' => 'The postal code matches, but the address was not verified.', 'MASTERCARD' => 'The postal code matches, but the address was not verified.', 'DISCOVER' => 'The postal code matches, but the address was not verified.'),
            'R' => array('VISA' => 'Retry the request.', 'MASTERCARD' => 'Retry the request.', 'DISCOVER' => 'Retry the request.', 'AMEX' => 'The system is unavailable.'),
            'S' => array('VISA' => 'Service not supported - N/A.', 'MASTERCARD' => 'Service not supported - N/A.', 'DISCOVER' => 'Service not supported - N/A.', 'AMEX' => 'Service not supported - N/A.'),
            'U' => array('VISA' => 'The service is unavailable.', 'MASTERCARD' => 'The service is unavailable.', 'DISCOVER' => 'The service is unavailable.', 'AMEX' => 'The information is not available.', 'MAESTRO' => 'The address was not checked, or the acquirer had no response. The service is not available.'),
            'W' => array('VISA' => 'Whole ZIP code.', 'MASTERCARD' => 'Whole ZIP code.', 'DISCOVER' => 'Whole ZIP code.', 'AMEX' => 'The cardholder name, address, and postal code are all incorrect.'),
            'X' => array('VISA' => 'Exact match of the address and the nine-digit ZIP code.', 'MASTERCARD' => 'Exact match of the address and the nine-digit ZIP code.', 'DISCOVER' => 'Exact match of the address and the nine-digit ZIP code.', 'AMEX' => 'The cardholder name, address, and postal code are all incorrect.'),
            'Y' => array('VISA' => 'The address and five-digit ZIP code match.', 'MASTERCARD' => 'The address and five-digit ZIP code match.', 'DISCOVER' => 'The address and five-digit ZIP code match.', 'AMEX' => 'The cardholder\'s address and postal code are both correct.'),
            'Z' => 'For Visa, Mastercard, or Discover transactions, the five-digit ZIP code matches but no address. For American Express, only the card holder postal code is correct.',
            'Null' => array('MAESTRO' => 'No AVS response was obtained.')
        );
        $this->cvv_code = array(
            '0' => array('MAESTRO' => 'The CVV2 matched.'),
            '1' => array('MAESTRO' => 'The CVV2 did not match.'),
            '2' => array('MAESTRO' => 'The merchant has not implemented CVV2 code handling.'),
            '3' => array('MAESTRO' => 'The merchant has indicated that CVV2 is not present on the card.'),
            '4' => array('MAESTRO' => 'The service is not available.'),
            'E' => array('VISA' => 'Error: Unrecognized or unknown response.', 'MASTERCARD' => 'Error: Unrecognized or unknown response.', 'DISCOVER' => 'Error: Unrecognized or unknown response.', 'AMEX' => 'Error: Unrecognized or unknown response.'),
            'I' => array('VISA' => 'Invalid or null value.', 'MASTERCARD' => 'Invalid or null value.', 'DISCOVER' => 'Invalid or null value.', 'AMEX' => 'Invalid or null value.'),
            'M' => array('VISA' => 'The CVV2/CSC matches.', 'MASTERCARD' => 'The CVV2/CSC matches.', 'DISCOVER' => 'The CVV2/CSC matches.', 'AMEX' => 'The CVV2/CSC matches.'),
            'N' => array('VISA' => 'The CVV2/CSC does not match.', 'MASTERCARD' => 'The CVV2/CSC does not match.', 'DISCOVER' => 'The CVV2/CSC does not match.', 'AMEX' => 'The CVV2/CSC does not match.'),
            'P' => array('VISA' => 'It was not processed.', 'MASTERCARD' => 'It was not processed.', 'DISCOVER' => 'It was not processed.', 'AMEX' => 'It was not processed.'),
            'S' => array('VISA' => 'The service is not supported.', 'MASTERCARD' => 'The service is not supported.', 'DISCOVER' => 'The service is not supported.', 'AMEX' => 'The service is not supported.'),
            'U' => array('VISA' => 'Unknown - the issuer is not certified.', 'MASTERCARD' => 'Unknown - the issuer is not certified.', 'DISCOVER' => 'Unknown - the issuer is not certified.', 'AMEX' => 'Unknown - the issuer is not certified.'),
            'X' => array('VISA' => 'No response.', 'MASTERCARD' => 'No response.', 'DISCOVER' => 'No response.', 'AMEX' => 'The service is not available.'),
            'Other' => array('VISA' => 'Error.', 'MASTERCARD' => 'Error.', 'DISCOVER' => 'Error.', 'AMEX' => 'Error.'),
        );
        $this->response_code = array(
            '1000' => 'PARTIAL_AUTHORIZATION.',
            '1300' => 'INVALID_DATA_FORMAT.',
            '1310' => 'INVALID_AMOUNT.',
            '1312' => 'INVALID_TRANSACTION_CARD_ISSUER_ACQUIRER.',
            '1317' => 'INVALID_CAPTURE_DATE.',
            '1320' => 'INVALID_CURRENCY_CODE.',
            '1330' => 'INVALID_ACCOUNT.',
            '1335' => 'INVALID_ACCOUNT_RECURRING.',
            '1340' => 'INVALID_TERMINAL.',
            '1350' => 'INVALID_MERCHANT.',
            '1352' => 'RESTRICTED_OR_INACTIVE_ACCOUNT.',
            '1360' => 'BAD_PROCESSING_CODE.',
            '1370' => 'INVALID_MCC.',
            '1380' => 'INVALID_EXPIRATION.',
            '1382' => 'INVALID_CARD_VERIFICATION_VALUE.',
            '1384' => 'INVALID_LIFE_CYCLE_OF_TRANSACTION.',
            '1390' => 'INVALID_ORDER.',
            '1393' => 'TRANSACTION_CANNOT_BE_COMPLETED.',
            '5100' => 'GENERIC_DECLINE.',
            '5110' => 'CVV2_FAILURE.',
            '5120' => 'INSUFFICIENT_FUNDS.',
            '5130' => 'INVALID_PIN.',
            '5135' => 'DECLINED_PIN_TRY_EXCEEDED.',
            '5140' => 'CARD_CLOSED.',
            '5150' => 'PICKUP_CARD_SPECIAL_CONDITIONS. Try using another card. Do not retry the same card.',
            '5160' => 'UNAUTHORIZED_USER.',
            '5170' => 'AVS_FAILURE.',
            '5180' => 'INVALID_OR_RESTRICTED_CARD. Try using another card. Do not retry the same card.',
            '5190' => 'SOFT_AVS.',
            '5200' => 'DUPLICATE_TRANSACTION.',
            '5210' => 'INVALID_TRANSACTION',
            '5400' => 'EXPIRED_CARD',
            '5500' => 'INCORRECT_PIN_REENTER',
            '5650' => 'DECLINED_SCA_REQUIRED',
            '5700' => 'TRANSACTION_NOT_PERMITTED. Outside of scope of accepted business.',
            '5710' => 'TX_ATTEMPTS_EXCEED_LIMIT.',
            '5800' => 'REVERSAL_REJECTED',
            '5900' => 'INVALID_ISSUE',
            '5910' => 'ISSUER_NOT_AVAILABLE_NOT_RETRIABLE',
            '5920' => 'ISSUER_NOT_AVAILABLE_RETRIABLE',
            '5930' => 'CARD_NOT_ACTIVATED',
            '5950' => 'DECLINED_DUE_TO_UPDATED_ACCOUNT. External decline as an updated card has been issued.',
            '6300' => 'ACCOUNT_NOT_ON_FILE',
            '7600' => 'APPROVED_NON_CAPTURE',
            '7700' => 'ERROR_3DS',
            '7710' => 'AUTHENTICATION_FAILED',
            '7800' => 'BIN_ERROR',
            '7900' => 'PIN_ERROR',
            '8000' => 'PROCESSOR_SYSTEM_ERROR',
            '8010' => 'HOST_KEY_ERROR',
            '8020' => 'CONFIGURATION_ERROR',
            '8030' => 'UNSUPPORTED_OPERATION',
            '8100' => 'FATAL_COMMUNICATION_ERROR',
            '8110' => 'RETRIABLE_COMMUNICATION_ERROR',
            '8220' => 'SYSTEM_UNAVAILABLE',
            '9100' => 'DECLINED_PLEASE_RETRY. Retry.',
            '9500' => 'SUSPECTED_FRAUD. Try using another card. Do not retry the same card.',
            '9510' => 'SECURITY_VIOLATION',
            '9520' => 'LOST_OR_STOLEN. Try using another card. Do not retry the same card.',
            '9530' => 'HOLD_CALL_CENTER. The merchant must call the number on the back of the card. POS scenario.',
            '9540' => 'REFUSED_CARD',
            '9600' => 'UNRECOGNIZED_RESPONSE_CODE',
            '0000' => 'APPROVED',
            '00N7' => 'CVV2_FAILURE_POSSIBLE_RETRY_WITH_CVV',
            '0100' => 'REFERRAL',
            '0390' => 'ACCOUNT_NOT_FOUND',
            '0500' => 'DO_NOT_HONOR',
            '0580' => 'UNAUTHORIZED_TRANSACTION',
            '0800' => 'BAD_RESPONSE_REVERSAL_REQUIRED',
            '0880' => 'CRYPTOGRAPHIC_FAILURE',
            '0R00' => 'CANCELLED_PAYMENT.',
            '10BR' => 'ISSUER_REJECTED',
            'PCNR' => 'CONTINGENCIES_NOT_RESOLVED',
            'PCVV' => 'CVV_FAILURE',
            'PP06' => 'ACCOUNT_CLOSED. A previously open account is now closed',
            'PPRN' => 'REATTEMPT_NOT_PERMITTED',
            'PPAD' => 'BILLING_ADDRESS',
            'PPAE' => 'AMEX_DISABLED',
            'PPAG' => 'ADULT_GAMING_UNSUPPORTED',
            'PPAI' => 'AMOUNT_INCOMPATIBLE',
            'PPAR' => 'AUTH_RESULT',
            'PPAU' => 'MCC_CODE',
            'PPAV' => 'ARC_AVS',
            'PPAX' => 'AMOUNT_EXCEEDED',
            'PPBG' => 'BAD_GAMING',
            'PPC2' => 'ARC_CVV',
            'PPCE' => 'CE_REGISTRATION_INCOMPLETE',
            'PPCO' => 'COUNTRY',
            'PPCR' => 'CREDIT_ERROR',
            'PPCT' => 'CARD_TYPE_UNSUPPORTED',
            'PPCU' => 'CURRENCY_USED_INVALID',
            'PPD3' => 'SECURE_ERROR_3DS',
            'PPDC' => 'DCC_UNSUPPORTED',
            'PPDI' => 'DINERS_REJECT',
            'PPDV' => 'AUTH_MESSAGE',
            'PPEF' => 'EXPIRED_FUNDING_INSTRUMENT',
            'PPEL' => 'EXCEEDS_FREQUENCY_LIMIT',
            'PPER' => 'INTERNAL_SYSTEM_ERROR',
            'PPEX' => 'EXPIRY_DATE',
            'PPFE' => 'FUNDING_SOURCE_ALREADY_EXISTS',
            'PPFI' => 'INVALID_FUNDING_INSTRUMENT',
            'PPFR' => 'RESTRICTED_FUNDING_INSTRUMENT',
            'PPFV' => 'FIELD_VALIDATION_FAILED',
            'PPGR' => 'GAMING_REFUND_ERROR',
            'PPH1' => 'H1_ERROR',
            'PPIF' => 'IDEMPOTENCY_FAILURE',
            'PPII' => 'INVALID_INPUT_FAILURE',
            'PPIM' => 'ID_MISMATCH',
            'PPIT' => 'INVALID_TRACE_ID',
            'PPLR' => 'LATE_REVERSAL',
            'PPLS' => 'LARGE_STATUS_CODE',
            'PPMB' => 'MISSING_BUSINESS_RULE_OR_DATA',
            'PPMC' => 'BLOCKED_Mastercard',
            'PPMD' => 'PPMD',
            'PPNC' => 'NOT_SUPPORTED_NRC',
            'PPNL' => 'EXCEEDS_NETWORK_FREQUENCY_LIMIT',
            'PPNT' => 'NETWORK_ERROR',
            'PPPH' => 'NO_PHONE_FOR_DCC_TRANSACTION',
            'PPPI' => 'INVALID_PRODUCT',
            'PPPM' => 'INVALID_PAYMENT_METHOD',
            'PPQC' => 'QUASI_CASH_UNSUPPORTED',
            'PPRE' => 'UNSUPPORT_REFUND_ON_PENDING_BC',
            'PPRF' => 'INVALID_PARENT_TRANSACTION_STATUS',
            'PPRR' => 'MERCHANT_NOT_REGISTERED',
            'PPS0' => 'BANKAUTH_ROW_MISMATCH',
            'PPS1' => 'BANKAUTH_ROW_SETTLED',
            'PPS2' => 'BANKAUTH_ROW_VOIDED',
            'PPS3' => 'BANKAUTH_EXPIRED',
            'PPS4' => 'CURRENCY_MISMATCH',
            'PPS5' => 'CREDITCARD_MISMATCH',
            'PPS6' => 'AMOUNT_MISMATCH',
            'PPSC' => 'ARC_SCORE',
            'PPSD' => 'STATUS_DESCRIPTION',
            'PPSE' => 'AMEX_DENIED',
            'PPTE' => 'VERIFICATION_TOKEN_EXPIRED',
            'PPTF' => 'INVALID_TRACE_REFERENCE',
            'PPTI' => 'INVALID_TRANSACTION_ID',
            'PPTR' => 'VERIFICATION_TOKEN_REVOKED',
            'PPTT' => 'TRANSACTION_TYPE_UNSUPPORTED',
            'PPTV' => 'INVALID_VERIFICATION_TOKEN',
            'PPUA' => 'USER_NOT_AUTHORIZED',
            'PPUC' => 'CURRENCY_CODE_UNSUPPORTED',
            'PPUE' => 'UNSUPPORT_ENTITY',
            'PPUI' => 'UNSUPPORT_INSTALLMENT',
            'PPUP' => 'UNSUPPORT_POS_FLAG',
            'PPUR' => 'UNSUPPORTED_REVERSAL',
            'PPVC' => 'VALIDATE_CURRENCY',
            'PPVE' => 'VALIDATION_ERROR',
            'PPVT' => 'VIRTUAL_TERMINAL_UNSUPPORTED',
        );
        $this->payment_advice_code = array(
            '21' => 'For Mastercard, the card holder has been unsuccessful at canceling recurring payment through merchant. Stop recurring payment requests. For Visa, all recurring payments were canceled for the card number requested. Stop recurring payment requests.',
            '01' => 'For Mastercard, expired card account upgrade or portfolio sale conversion. Obtain new account information before next billing cycle.',
            '02' => 'For Mastercard, over credit limit or insufficient funds. Retry the transaction 72 hours later. For Visa, the card holder wants to stop only one specific payment in the recurring payment relationship. The merchant must NOT resubmit the same transaction. The merchant can continue the billing process in the subsequent billing period.',
            '03' => 'For Mastercard, account closed as fraudulent. Obtain another type of payment from customer due to account being closed or fraud. Possible reason: Account closed as fraudulent. For Visa, the card holder wants to stop all recurring payment transactions for a specific merchant. Stop recurring payment requests.',
        );
    }
}
